import React, { useState, useCallback } from 'react';
import { generateImage } from '../services/geminiService';
import { ASPECT_RATIOS } from '../constants';
import Spinner from './common/Spinner';

const ImageGenerator: React.FC = () => {
    const [prompt, setPrompt] = useState<string>('');
    const [aspectRatio, setAspectRatio] = useState<string>(ASPECT_RATIOS[0]);
    const [generatedImage, setGeneratedImage] = useState<string | null>(null);
    const [isLoading, setIsLoading] = useState<boolean>(false);
    const [error, setError] = useState<string>('');

    const handleGenerate = useCallback(async () => {
        if (!prompt.trim()) {
            setError('Please enter a prompt.');
            return;
        }
        setIsLoading(true);
        setError('');
        setGeneratedImage(null);
        try {
            const imageBytes = await generateImage(prompt, aspectRatio);
            if (imageBytes) {
                setGeneratedImage(`data:image/png;base64,${imageBytes}`);
            } else {
                setError('Failed to generate image. The model might have refused the prompt.');
            }
        } catch (err) {
            setError('An error occurred while generating the image.');
            console.error(err);
        } finally {
            setIsLoading(false);
        }
    }, [prompt, aspectRatio]);

    return (
        <div className="max-w-4xl mx-auto p-4 space-y-6">
            <h2 className="text-2xl font-bold text-center text-purple-400">Image Generation</h2>
            <div className="bg-gray-800 p-6 rounded-lg shadow-lg space-y-4">
                <div>
                    <label htmlFor="prompt-gen" className="block text-sm font-medium text-gray-300 mb-2">Prompt</label>
                    <textarea
                        id="prompt-gen"
                        value={prompt}
                        onChange={(e) => setPrompt(e.target.value)}
                        className="w-full p-3 bg-gray-700 rounded-lg focus:outline-none focus:ring-2 focus:ring-purple-500 h-24"
                        placeholder="e.g., A photo of an astronaut riding a horse on Mars"
                    />
                </div>

                <div>
                    <label className="block text-sm font-medium text-gray-300 mb-2">Aspect Ratio</label>
                    <div className="flex flex-wrap gap-2">
                        {ASPECT_RATIOS.map((ratio) => (
                            <button
                                key={ratio}
                                onClick={() => setAspectRatio(ratio)}
                                className={`px-4 py-2 text-sm font-semibold rounded-full transition ${aspectRatio === ratio ? 'bg-purple-600 text-white' : 'bg-gray-700 text-gray-300 hover:bg-gray-600'}`}
                            >{ratio}</button>
                        ))}
                    </div>
                </div>

                <button
                    onClick={handleGenerate}
                    disabled={isLoading || !prompt}
                    className="w-full p-3 bg-purple-600 rounded-lg text-white font-semibold disabled:bg-gray-600 disabled:cursor-not-allowed hover:bg-purple-700 transition flex items-center justify-center"
                >
                    {isLoading ? <Spinner /> : 'Generate Image'}
                </button>
            </div>

            {error && <p className="text-red-400 text-center">{error}</p>}

            {generatedImage && (
                <div className="bg-gray-800 p-6 rounded-lg shadow-lg">
                    <h3 className="text-lg font-semibold mb-2 text-purple-300">Generated Image</h3>
                    <img src={generatedImage} alt="Generated by AI" className="max-w-full mx-auto rounded-lg" />
                </div>
            )}
        </div>
    );
};

export default ImageGenerator;
